
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVDER = 5;
  public static final int AND = 19;
  public static final int MENOS = 15;
  public static final int PUNTO = 10;
  public static final int DOSPUNTOS = 12;
  public static final int OR = 20;
  public static final int IGUAL = 9;
  public static final int LETRA = 18;
  public static final int DOLLAR = 13;
  public static final int SYMBOL = 24;
  public static final int NOT = 21;
  public static final int PARIZQ = 3;
  public static final int PARDER = 4;
  public static final int vacio = 30;
  public static final int ID = 23;
  public static final int POR = 16;
  public static final int VIRGUILLA = 28;
  public static final int EQUALS = 17;
  public static final int COMA = 11;
  public static final int PR_CONJ = 29;
  public static final int EOF = 0;
  public static final int DIGITO = 22;
  public static final int CHAREX = 27;
  public static final int COMDOBLES = 26;
  public static final int error = 1;
  public static final int CORIZQ = 8;
  public static final int CORDER = 7;
  public static final int MAS = 14;
  public static final int UNKNOWN = 25;
  public static final int LLAVIZQ = 6;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVDER",
  "LLAVIZQ",
  "CORDER",
  "CORIZQ",
  "IGUAL",
  "PUNTO",
  "COMA",
  "DOSPUNTOS",
  "DOLLAR",
  "MAS",
  "MENOS",
  "POR",
  "EQUALS",
  "LETRA",
  "AND",
  "OR",
  "NOT",
  "DIGITO",
  "ID",
  "SYMBOL",
  "UNKNOWN",
  "COMDOBLES",
  "CHAREX",
  "VIRGUILLA",
  "PR_CONJ",
  "vacio"
  };
}

